export const SITE_CONFIG = {
  name: 'INSAF LIMITED',
  tagline: 'RAJUK-Approved Architectural Excellence',
  description: '530+ অনুমোদিত প্রকল্প | ১২ বছরের অভিজ্ঞতা | ঢাকার সেরা আর্কিটেক্ট',
  url: 'https://insaflimited.com',
  email: 'info@insaflimited.com',
  phone: '+880 1XXX-XXXXXX',
  whatsapp: '8801XXXXXXXXX',
  address: 'House 123, Road 45, Gulshan-2, Dhaka 1212',
  social: {
    facebook: 'https://facebook.com/insaflimited',
    linkedin: 'https://linkedin.com/company/insaflimited',
    youtube: 'https://youtube.com/@insaflimited',
    instagram: 'https://instagram.com/insaflimited',
  },
} as const

export const NAVIGATION_LINKS = [
  { href: '/', label: 'হোম', labelEn: 'Home' },
  { href: '/about', label: 'আমাদের সম্পর্কে', labelEn: 'About' },
  { href: '/services', label: 'সেবাসমূহ', labelEn: 'Services' },
  { href: '/portfolio', label: 'প্রকল্পসমূহ', labelEn: 'Portfolio' },
  { href: '/blog', label: 'ব্লগ', labelEn: 'Blog' },
  { href: '/contact', label: 'যোগাযোগ', labelEn: 'Contact' },
] as const

export const SERVICES = [
  {
    id: 1,
    step: '০১',
    title: 'Land Feasibility & DAP Check',
    titleBn: 'জমি যাচাই ও DAP বিশ্লেষণ',
    icon: '📐',
    description: 'জমি কি buildable? setback ঠিক আছে? এখনই জানুন।',
    details: 'আমরা আপনার জমির সম্পূর্ণ legal এবং technical feasibility check করি — DAP compliance, road width, setback requirements সহ।',
    features: [
      'DAP Compliance Analysis',
      'Road Width Verification',
      'Setback Calculation',
      'FAR/Ground Coverage Check',
      'Legal Documentation Review',
    ],
  },
  {
    id: 2,
    step: '০২',
    title: 'Architectural Concept & 3D',
    titleBn: 'আর্কিটেকচারাল ধারণা ও 3D ডিজাইন',
    icon: '🏛️',
    description: 'আপনার taste + zoning law — একসাথে।',
    details: 'আধুনিক 3D visualization সহ আপনার স্বপ্নের বাড়ির design তৈরি করি যা RAJUK guidelines মেনে চলে।',
    features: [
      'Custom Floor Plans',
      'Photorealistic 3D Renders',
      'Interior Layout Design',
      'Elevation & Facade Design',
      'Virtual Walkthroughs',
    ],
  },
  {
    id: 3,
    step: '০৩',
    title: 'Structural Design (Load + Safety)',
    titleBn: 'স্ট্রাকচারাল ডিজাইন (লোড ও নিরাপত্তা)',
    icon: '🏗️',
    description: 'আমরা শুধু architect না — in-house structural engineers আছে।',
    details: 'BNBC code অনুযায়ী সম্পূর্ণ structural calculation — foundation, column, beam, slab সব কিছুর engineering drawing।',
    features: [
      'BNBC Compliant Calculations',
      'Foundation Design',
      'RCC Detailing',
      'Load Bearing Analysis',
      'Earthquake Resistance Design',
    ],
  },
  {
    id: 4,
    step: '০৪',
    title: 'RAJUK Submission & Follow-up',
    titleBn: 'RAJUK জমা ও ফলো-আপ',
    icon: '📋',
    description: 'File জমা থেকে approval — আমরা handle করি।',
    details: 'সম্পূর্ণ documentation, submission এবং approval পর্যন্ত follow-up — আপনাকে কোথাও যেতে হবে না।',
    features: [
      'Complete Documentation',
      'RAJUK Plan Submission',
      'Approval Follow-up',
      'Revision Management',
      'NOC Collection',
    ],
  },
  {
    id: 5,
    step: '০৫',
    title: 'Construction Guidance',
    titleBn: 'নির্মাণ তত্ত্বাবধান',
    icon: '👷',
    description: 'Drawing থেকে execution — consistency থাকুক।',
    details: 'প্রয়োজনে site visit, contractor coordination এবং quality check — যাতে design অনুযায়ী নির্মাণ হয়।',
    features: [
      'Site Supervision',
      'Quality Control',
      'Contractor Coordination',
      'Material Specification',
      'Progress Monitoring',
    ],
  },
] as const

export const PORTFOLIO_RESIDENTIAL = [
  {
    id: 1,
    name: 'Villa Serenity',
    type: '5-bed duplex',
    location: 'Bashundhara R/A',
    year: '2024',
    area: '3,800 sq ft',
    image: '/portfolio/villa-serenity.jpg',
    tags: ['Modern', 'Luxury', 'RAJUK Approved'],
  },
  {
    id: 2,
    name: 'The White Residence',
    type: 'Modern minimalist',
    location: 'Dhanmondi',
    year: '2023',
    area: '2,500 sq ft',
    image: '/portfolio/white-residence.jpg',
    tags: ['Minimalist', 'Contemporary', 'Eco-friendly'],
  },
  {
    id: 3,
    name: 'Garden View Home',
    type: 'Eco-friendly design',
    location: 'Uttara',
    year: '2024',
    area: '4,200 sq ft',
    image: '/portfolio/garden-view.jpg',
    tags: ['Green Building', 'Sustainable', 'Family Home'],
  },
] as const

export const PORTFOLIO_COMMERCIAL = [
  {
    id: 1,
    name: 'Trade Tower',
    type: 'Mixed-use',
    floors: 'G+8',
    feature: 'Max commercial units',
    area: '45,000 sq ft',
    image: '/portfolio/trade-tower.jpg',
    tags: ['Commercial', 'Mixed-use', 'High-rise'],
  },
  {
    id: 2,
    name: 'Apex Plaza',
    type: 'Retail complex',
    floors: 'G+6',
    feature: 'Fire safety optimized',
    area: '32,000 sq ft',
    image: '/portfolio/apex-plaza.jpg',
    tags: ['Retail', 'Shopping', 'Modern'],
  },
  {
    id: 3,
    name: 'Business Hub',
    type: 'Corporate office',
    floors: 'G+10',
    feature: 'Smart building',
    area: '65,000 sq ft',
    image: '/portfolio/business-hub.jpg',
    tags: ['Office', 'Corporate', 'Tech-enabled'],
  },
] as const

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'জনাব আহমেদ হোসেন',
    role: 'Homeowner, Gulshan',
    image: '/testimonials/ahmed.jpg',
    rating: 5,
    text: 'আমার স্বপ্নের বাড়ি তৈরিতে INSAF Limited এর অবদান অসাধারণ। RAJUK approval প্রক্রিয়া এত সহজ করে দিয়েছে যে আমি বিশ্বাসই করতে পারছিলাম না।',
    project: 'Villa Serenity',
    video: 'https://youtube.com/watch?v=xxxxx',
  },
  {
    id: 2,
    name: 'Mrs. Tahmina Rahman',
    role: 'Developer, Uttara',
    image: '/testimonials/tahmina.jpg',
    rating: 5,
    text: 'Professional, transparent, and delivered on time. Their structural team saved us from potential future disasters. Worth every taka!',
    project: 'Apex Plaza',
    video: null,
  },
  {
    id: 3,
    name: 'ইঞ্জিনিয়ার মাহমুদুল হক',
    role: 'Plot Owner, Bashundhara',
    image: '/testimonials/mahmud.jpg',
    rating: 5,
    text: '530+ প্রজেক্ট এর track record দেখে কাজ দিয়েছিলাম। এখন বুঝতে পারছি কেন তারা সেরা। Design, execution, approval সব কিছুতে excellence!',
    project: 'Garden View Home',
    video: 'https://youtube.com/watch?v=yyyyy',
  },
] as const

export const TRUST_BADGES = [
  {
    icon: '📄',
    title: 'RAJUK NOC',
    titleBn: 'RAJUK অনুমোদনপত্র',
    description: '১০০% approval সাফল্য',
  },
  {
    icon: '🧪',
    title: 'Soil Test Report',
    titleBn: 'মাটি পরীক্ষা রিপোর্ট',
    description: 'BNBC অনুযায়ী সম্পন্ন',
  },
  {
    icon: '📐',
    title: 'Structural Drawing',
    titleBn: 'কাঠামো নকশা',
    description: 'Professional engineers দ্বারা',
  },
  {
    icon: '🔥',
    title: 'Fire Safety',
    titleBn: 'অগ্নি নিরাপত্তা সনদ',
    description: 'Fire Service approved',
  },
] as const

export const BLOG_POSTS = [
  {
    id: 1,
    title: 'কেন অনেক বাড়ি RAJUK pass করে না?',
    subtitle: '৫টি লুকানো ভুল',
    category: 'RAJUK Guide',
    categoryColor: 'bg-red-100 text-red-600',
    excerpt: 'RAJUK rejection এর পেছনে যে common mistakes থাকে তা জেনে নিন...',
    image: '/blog/rajuk-mistakes.jpg',
    author: 'Ar. Kamrul Islam',
    date: '২০ জানুয়ারি, ২০২৪',
    readTime: '৮ মিনিট',
    slug: 'rajuk-common-mistakes',
  },
  {
    id: 2,
    title: 'Commercial ভবনে ROI বাড়াতে',
    subtitle: 'Floor planning এর বিজ্ঞান',
    category: 'Commercial',
    categoryColor: 'bg-blue-100 text-blue-600',
    excerpt: 'একই জমিতে কীভাবে বেশি rentable area তৈরি করবেন...',
    image: '/blog/commercial-roi.jpg',
    author: 'Ar. Farzana Ahmed',
    date: '১৫ জানুয়ারি, ২০২৪',
    readTime: '১০ মিনিট',
    slug: 'commercial-floor-planning',
  },
  {
    id: 3,
    title: 'আপনার architect কি structural engineer-ও?',
    subtitle: 'না হলে risk আছে',
    category: 'Safety',
    categoryColor: 'bg-orange-100 text-orange-600',
    excerpt: 'শুধু design দিয়ে কাজ হয় না — structural calculation জরুরি কেন...',
    image: '/blog/structural-importance.jpg',
    author: 'Engr. Tarek Rahman',
    date: '১০ জানুয়ারি, ২০২৪',
    readTime: '৬ মিনিট',
    slug: 'structural-engineer-importance',
  },
] as const

export const FAQ_DATA = [
  {
    question: 'RAJUK approval এ কতদিন সময় লাগে?',
    answer: 'সাধারণত ৩-৬ মাস। তবে আমরা proper documentation এর মাধ্যমে এই সময় কমিয়ে আনার চেষ্টা করি। আমাদের track record অনুযায়ী গড়ে ৪ মাস।',
  },
  {
    question: 'Architectural ফি কত?',
    answer: 'প্রজেক্টের ধরণ ও সাইজের উপর নির্ভর করে। Residential এর জন্য সাধারণত built-up area এর ৳৮০-১২০/sqft। Free consultation এ বিস্তারিত জানানো হয়।',
  },
  {
    question: 'শুধু design নিব, নাকি পুরো package?',
    answer: 'দুটোই সম্ভব। তবে RAJUK approval পর্যন্ত নিলে আমরা পুরো দায়িত্ব নিই। শুধু design নিলে submission আপনাকেই করতে হবে।',
  },
  {
    question: 'Structural design আলাদা খরচ?',
    answer: 'না। আমাদের architectural package এ structural engineering included থাকে। কারণ আমরা বিশ্বাস করি এটা optional না, mandatory।',
  },
  {
    question: 'Construction supervision করেন?',
    answer: 'হ্যাঁ, optional হিসেবে। Monthly বা milestone-based visit packages আছে। এতে design consistency নিশ্চিত হয়।',
  },
] as const